services:
  db:
    image: postgres:18
    container_name: vending-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  backend:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: "docker.env"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: "docker.env"   # optional if your frontend uses env variables
    depends_on:
      - backend
    ports:
      - "3000:3000"          # match the EXPOSE in your frontend Dockerfile
    restart: unless-stopped
volumes:
  db-data:

