// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_product.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductRows = `-- name: CountProductRows :one
SELECT COUNT(*)
FROM product_info
WHERE date_deleted IS NULL
    AND ($1 = '' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountProductRows(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countProductRows, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :exec

INSERT INTO product_info (name, cost_cents, price_cents)
VALUES ( $1, $2, $3 )
`

type CreateProductParams struct {
	Name       string
	CostCents  int32
	PriceCents int32
}

// code: language=postgres
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct, arg.Name, arg.CostCents, arg.PriceCents)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE product_info
SET date_deleted = NOW()
WHERE product_id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, productID)
	return err
}

const getProducts = `-- name: GetProducts :many
SELECT
    product_id,
    name,
    cost_cents,
    price_cents,
    date_created,
    date_modified,
    date_deleted
FROM product_info
WHERE date_deleted IS NULL
    AND ($1 = '' OR name ILIKE '%' || $1 || '%')
ORDER BY
    CASE WHEN $2 = 'name' AND $3 = 'asc' THEN LOWER(name) END ASC,
    CASE WHEN $2 = 'name' AND $3 = 'desc' THEN LOWER(name) END DESC,
    CASE WHEN $2 = 'cost' AND $3 = 'asc' THEN cost_cents END ASC,
    CASE WHEN $2 = 'cost' AND $3 = 'desc' THEN cost_cents END DESC,
    CASE WHEN $2 = 'price' AND $3 = 'asc' THEN price_cents END ASC,
    CASE WHEN $2 = 'price' AND $3 = 'desc' THEN price_cents END DESC,
    CASE WHEN $2 = 'created_at' AND $3 = 'asc' THEN date_created END ASC,
    CASE WHEN $2 = 'created_at' AND $3 = 'desc' THEN date_created END DESC,
    LOWER(name) ASC,
    product_id ASC
LIMIT $5
OFFSET $4
`

type GetProductsParams struct {
	Search     interface{}
	SortBy     interface{}
	SortDir    interface{}
	PageOffset int32
	NumRows    int32
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]ProductInfo, error) {
	rows, err := q.db.Query(ctx, getProducts,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.NumRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductInfo
	for rows.Next() {
		var i ProductInfo
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.CostCents,
			&i.PriceCents,
			&i.DateCreated,
			&i.DateModified,
			&i.DateDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductCost = `-- name: UpdateProductCost :exec
UPDATE product_info
SET cost_cents = $1
WHERE product_id = $2
`

type UpdateProductCostParams struct {
	CostCents int32
	ProductID pgtype.UUID
}

func (q *Queries) UpdateProductCost(ctx context.Context, arg UpdateProductCostParams) error {
	_, err := q.db.Exec(ctx, updateProductCost, arg.CostCents, arg.ProductID)
	return err
}

const updateProductName = `-- name: UpdateProductName :exec
UPDATE product_info
SET name = $1
WHERE product_id = $2
`

type UpdateProductNameParams struct {
	Name      string
	ProductID pgtype.UUID
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) error {
	_, err := q.db.Exec(ctx, updateProductName, arg.Name, arg.ProductID)
	return err
}

const updateProductPrice = `-- name: UpdateProductPrice :exec
UPDATE product_info
SET price_cents = $1
WHERE product_id = $2
`

type UpdateProductPriceParams struct {
	PriceCents int32
	ProductID  pgtype.UUID
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error {
	_, err := q.db.Exec(ctx, updateProductPrice, arg.PriceCents, arg.ProductID)
	return err
}
