// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 003_transaction.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionRows = `-- name: CountTransactionRows :one
SELECT COUNT(*)
FROM transactions as t
JOIN product_info p ON t.product_id = p.product_id
WHERE $1 = '' OR p.name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountTransactionRows(ctx context.Context, search interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionRows, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransactions = `-- name: GetTransactions :many

SELECT
    t.transaction_id,
    t.price_at_sale_cents,
    t.date_sold,
    p.name
FROM transactions as t
JOIN product_info p ON t.product_id = p.product_id
WHERE $1 = '' OR p.name ILIKE '%' || $1 || '%'
ORDER BY
    CASE WHEN $2 = 'product' AND $3 = 'asc' THEN LOWER(p.name) END ASC,
    CASE WHEN $2 = 'product' AND $3 = 'desc' THEN LOWER(p.name) END DESC,
    CASE WHEN $2 = 'date' AND $3 = 'asc' THEN t.date_sold END ASC,
    CASE WHEN $2 = 'date' AND $3 = 'desc' THEN t.date_sold END DESC,
    CASE WHEN $2 = 'price' AND $3 = 'asc' THEN t.price_at_sale_cents END ASC,
    CASE WHEN $2 = 'price' AND $3 = 'desc' THEN t.price_at_sale_cents END DESC,
    t.date_sold DESC,
    t.transaction_id ASC
LIMIT $5
OFFSET $4
`

type GetTransactionsParams struct {
	Search     interface{}
	SortBy     interface{}
	SortDir    interface{}
	PageOffset int32
	NumRows    int32
}

type GetTransactionsRow struct {
	TransactionID    pgtype.UUID
	PriceAtSaleCents int32
	DateSold         pgtype.Timestamptz
	Name             string
}

// code: language=postgres
func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]GetTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getTransactions,
		arg.Search,
		arg.SortBy,
		arg.SortDir,
		arg.PageOffset,
		arg.NumRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.PriceAtSaleCents,
			&i.DateSold,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
