// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 004_users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role, created_by)
VALUES ($1, $2, $3, $4)
RETURNING user_id, email, password_hash, role, is_active, created_by, date_created, date_modified
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedBy,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE user_id = $1
RETURNING user_id, email, password_hash, role, is_active, created_by, date_created, date_modified
`

func (q *Queries) DeleteUser(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedBy,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password_hash, role, is_active, created_by, date_created, date_modified FROM users WHERE email = $1 AND is_active = TRUE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedBy,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, email, password_hash, role, is_active, created_by, date_created, date_modified FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedBy,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, email, role, is_active, created_by, date_created
FROM users
WHERE is_active = TRUE
ORDER BY date_created ASC
`

type ListUsersRow struct {
	UserID      pgtype.UUID
	Email       string
	Role        string
	IsActive    bool
	CreatedBy   pgtype.UUID
	DateCreated pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.IsActive,
			&i.CreatedBy,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users
SET password_hash = $1
WHERE user_id = $2
RETURNING user_id, email, password_hash, role, is_active, created_by, date_created, date_modified
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	UserID       pgtype.UUID
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedBy,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $1 WHERE user_id = $2 RETURNING user_id, email, password_hash, role, is_active, created_by, date_created, date_modified
`

type UpdateUserRoleParams struct {
	Role   string
	UserID pgtype.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedBy,
		&i.DateCreated,
		&i.DateModified,
	)
	return i, err
}
