// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 005_settings.sql

package repository

import (
	"context"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT id, low_stock_threshold FROM app_settings WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(&i.ID, &i.LowStockThreshold)
	return i, err
}

const updateLowStockThreshold = `-- name: UpdateLowStockThreshold :one
UPDATE app_settings SET low_stock_threshold = $1 WHERE id = 1 RETURNING id, low_stock_threshold
`

func (q *Queries) UpdateLowStockThreshold(ctx context.Context, lowStockThreshold int32) (AppSetting, error) {
	row := q.db.QueryRow(ctx, updateLowStockThreshold, lowStockThreshold)
	var i AppSetting
	err := row.Scan(&i.ID, &i.LowStockThreshold)
	return i, err
}
