// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 006_analytics.sql

package repository

import (
	"context"
)

const getDailyRevenueAndProfit = `-- name: GetDailyRevenueAndProfit :many

SELECT
    DATE(t.date_sold)::text AS sale_date,
    SUM(t.price_at_sale_cents) AS revenue_cents,
    SUM(t.price_at_sale_cents - COALESCE(p.cost_cents, 0)) AS profit_cents
FROM transactions t
LEFT JOIN product_info p ON t.product_id = p.product_id AND p.date_deleted IS NULL
WHERE t.date_sold >= CURRENT_DATE - ($1::int || ' days')::INTERVAL + INTERVAL '1 day'
GROUP BY DATE(t.date_sold)
ORDER BY sale_date ASC
`

type GetDailyRevenueAndProfitRow struct {
	SaleDate     string
	RevenueCents int64
	ProfitCents  int64
}

// code: language=postgres
// Returns one row per day for the last N days.
// This codebase stores one transaction row per sold item, so revenue and profit
// are summed directly from each row without a quantity multiplier.
func (q *Queries) GetDailyRevenueAndProfit(ctx context.Context, days int32) ([]GetDailyRevenueAndProfitRow, error) {
	rows, err := q.db.Query(ctx, getDailyRevenueAndProfit, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyRevenueAndProfitRow
	for rows.Next() {
		var i GetDailyRevenueAndProfitRow
		if err := rows.Scan(&i.SaleDate, &i.RevenueCents, &i.ProfitCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryHealth = `-- name: GetInventoryHealth :many
SELECT
    i.slot_label AS slot_id,
    COALESCE(i.quantity, 0) AS quantity,
    COALESCE(p.name, '') AS product_name,
    COALESCE(p.cost_cents, 0) AS cost_cents,
    COALESCE(p.price_cents, 0) AS price_cents
FROM inventory i
LEFT JOIN product_info p ON i.product_id = p.product_id AND p.date_deleted IS NULL
ORDER BY i.slot_id ASC
`

type GetInventoryHealthRow struct {
	SlotID      string
	Quantity    int32
	ProductName string
	CostCents   int32
	PriceCents  int32
}

// Current quantity per slot with product name and cost/price for margin calculation.
func (q *Queries) GetInventoryHealth(ctx context.Context) ([]GetInventoryHealthRow, error) {
	rows, err := q.db.Query(ctx, getInventoryHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryHealthRow
	for rows.Next() {
		var i GetInventoryHealthRow
		if err := rows.Scan(
			&i.SlotID,
			&i.Quantity,
			&i.ProductName,
			&i.CostCents,
			&i.PriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesHeatmap = `-- name: GetSalesHeatmap :many
SELECT
    DATE(date_sold)::text AS sale_date,
    COUNT(*) AS transaction_count,
    SUM(price_at_sale_cents) AS revenue_cents
FROM transactions
WHERE date_sold >= CURRENT_DATE - INTERVAL '27 days'
GROUP BY DATE(date_sold)
ORDER BY sale_date ASC
`

type GetSalesHeatmapRow struct {
	SaleDate         string
	TransactionCount int64
	RevenueCents     int64
}

// Transaction count and revenue per calendar day for the last 28 days.
func (q *Queries) GetSalesHeatmap(ctx context.Context) ([]GetSalesHeatmapRow, error) {
	rows, err := q.db.Query(ctx, getSalesHeatmap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSalesHeatmapRow
	for rows.Next() {
		var i GetSalesHeatmapRow
		if err := rows.Scan(&i.SaleDate, &i.TransactionCount, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopProducts = `-- name: GetTopProducts :many
SELECT
    p.name AS product_name,
    COUNT(*) AS units_sold,
    SUM(t.price_at_sale_cents - COALESCE(p.cost_cents, 0)) AS profit_cents
FROM transactions t
JOIN product_info p ON t.product_id = p.product_id
WHERE p.date_deleted IS NULL
    AND t.date_sold >= CURRENT_DATE - ($1::int || ' days')::INTERVAL + INTERVAL '1 day'
GROUP BY p.product_id, p.name
ORDER BY units_sold DESC, LOWER(p.name) ASC
`

type GetTopProductsRow struct {
	ProductName string
	UnitsSold   int64
	ProfitCents int64
}

// Units sold and profit per product for the last N days.
func (q *Queries) GetTopProducts(ctx context.Context, days int32) ([]GetTopProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopProducts, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopProductsRow
	for rows.Next() {
		var i GetTopProductsRow
		if err := rows.Scan(&i.ProductName, &i.UnitsSold, &i.ProfitCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
