// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentProducts = `-- name: GetCurrentProducts :many

SELECT
    cp.slot_id,
    cp.quantity,
    cp.date_added,
    pi.name,
    pi.price_cents,
    pi.product_id
FROM inventory cp
LEFT JOIN product_info pi ON cp.product_id = pi.product_id
`

type GetCurrentProductsRow struct {
	SlotID     int32
	Quantity   pgtype.Int4
	DateAdded  pgtype.Timestamptz
	Name       pgtype.Text
	PriceCents pgtype.Int4
	ProductID  pgtype.UUID
}

// code: language=postgres
func (q *Queries) GetCurrentProducts(ctx context.Context) ([]GetCurrentProductsRow, error) {
	rows, err := q.db.Query(ctx, getCurrentProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCurrentProductsRow
	for rows.Next() {
		var i GetCurrentProductsRow
		if err := rows.Scan(
			&i.SlotID,
			&i.Quantity,
			&i.DateAdded,
			&i.Name,
			&i.PriceCents,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProduct = `-- name: InsertProduct :exec
UPDATE inventory
SET
    product_id = $1,
    quantity = $2,
    date_added = NOW()
WHERE slot_id = $3
`

type InsertProductParams struct {
	ProductID pgtype.UUID
	Quantity  pgtype.Int4
	SlotID    int32
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.Exec(ctx, insertProduct, arg.ProductID, arg.Quantity, arg.SlotID)
	return err
}

const unassignSlot = `-- name: UnassignSlot :exec
UPDATE inventory
SET
    product_id = NULL,
    quantity = NULL,
    date_added = NULL
WHERE slot_id = $1
`

func (q *Queries) UnassignSlot(ctx context.Context, slotID int32) error {
	_, err := q.db.Exec(ctx, unassignSlot, slotID)
	return err
}

const updateQuantity = `-- name: UpdateQuantity :exec
UPDATE inventory
SET quantity = $1
WHERE slot_id = $2
`

type UpdateQuantityParams struct {
	Quantity pgtype.Int4
	SlotID   int32
}

func (q *Queries) UpdateQuantity(ctx context.Context, arg UpdateQuantityParams) error {
	_, err := q.db.Exec(ctx, updateQuantity, arg.Quantity, arg.SlotID)
	return err
}
