// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearInventorySlot = `-- name: ClearInventorySlot :exec
UPDATE inventory
SET
    product_id = NULL,
    quantity   = NULL
WHERE slot_id = $1
`

func (q *Queries) ClearInventorySlot(ctx context.Context, slotID int32) error {
	_, err := q.db.Exec(ctx, clearInventorySlot, slotID)
	return err
}

const countInventoryRows = `-- name: CountInventoryRows :one

SELECT COUNT(*) from inventory
`

// code: language=postgres
func (q *Queries) CountInventoryRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryRows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInventory = `-- name: GetInventory :many
SELECT
    cp.slot_id,
    cp.slot_label,
    cp.quantity,
    cp.date_added,
    pi.name,
    pi.price_cents,
    pi.product_id
FROM inventory cp
LEFT JOIN product_info pi ON cp.product_id = pi.product_id
ORDER BY cp.slot_id
LIMIT $2
OFFSET $1
`

type GetInventoryParams struct {
	PageOffset int32
	NumRows    int32
}

type GetInventoryRow struct {
	SlotID     int32
	SlotLabel  string
	Quantity   pgtype.Int4
	DateAdded  pgtype.Timestamptz
	Name       pgtype.Text
	PriceCents pgtype.Int4
	ProductID  pgtype.UUID
}

func (q *Queries) GetInventory(ctx context.Context, arg GetInventoryParams) ([]GetInventoryRow, error) {
	rows, err := q.db.Query(ctx, getInventory, arg.PageOffset, arg.NumRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryRow
	for rows.Next() {
		var i GetInventoryRow
		if err := rows.Scan(
			&i.SlotID,
			&i.SlotLabel,
			&i.Quantity,
			&i.DateAdded,
			&i.Name,
			&i.PriceCents,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :exec

UPDATE inventory
SET
    product_id = COALESCE($1, product_id),
    quantity   = COALESCE($2, quantity)
WHERE slot_id = $3
`

type UpdateInventoryParams struct {
	ProductID pgtype.UUID
	Quantity  pgtype.Int4
	SlotID    int32
}

// I have to pass this in from the frontend
func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error {
	_, err := q.db.Exec(ctx, updateInventory, arg.ProductID, arg.Quantity, arg.SlotID)
	return err
}
