// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppSetting struct {
	ID                int32
	LowStockThreshold int32
}

type Inventory struct {
	SlotID    int32
	SlotLabel string
	ProductID pgtype.UUID
	Quantity  pgtype.Int4
	DateAdded pgtype.Timestamptz
}

type ProductInfo struct {
	ProductID    pgtype.UUID
	Name         string
	CostCents    int32
	PriceCents   int32
	DateCreated  pgtype.Timestamptz
	DateModified pgtype.Timestamptz
	DateDeleted  pgtype.Timestamptz
}

type Transaction struct {
	TransactionID    pgtype.UUID
	ProductID        pgtype.UUID
	PriceAtSaleCents int32
	DateSold         pgtype.Timestamptz
}

type User struct {
	UserID       pgtype.UUID
	Email        string
	PasswordHash string
	Role         string
	IsActive     bool
	CreatedBy    pgtype.UUID
	DateCreated  pgtype.Timestamptz
	DateModified pgtype.Timestamptz
}
