// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrentProduct struct {
	SlotID    int32
	ProductID pgtype.UUID
	Quantity  int32
	DateAdded pgtype.Timestamptz
}

type ProductInfo struct {
	ProductID    pgtype.UUID
	Name         string
	Price        pgtype.Numeric
	DateCreated  pgtype.Timestamptz
	DateModified pgtype.Timestamptz
}

type Transaction struct {
	TransactionID pgtype.UUID
	ProductID     pgtype.UUID
	PriceAtSale   pgtype.Numeric
	DateSold      pgtype.Timestamptz
}
