// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	SlotID    int32
	SlotLabel string
	ProductID pgtype.UUID
	Quantity  pgtype.Int4
	DateAdded pgtype.Timestamptz
}

type ProductInfo struct {
	ProductID    pgtype.UUID
	Name         string
	PriceCents   int32
	DateCreated  pgtype.Timestamptz
	DateModified pgtype.Timestamptz
}

type Transaction struct {
	TransactionID    pgtype.UUID
	ProductID        pgtype.UUID
	PriceAtSaleCents int32
	DateSold         pgtype.Timestamptz
}
