// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :exec

INSERT INTO product_info (name, price_cents)
VALUES ( $1, $2 )
`

type CreateProductParams struct {
	Name       string
	PriceCents int32
}

// code: language=postgres
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct, arg.Name, arg.PriceCents)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product_info
WHERE product_id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, productID)
	return err
}

const getProducts = `-- name: GetProducts :many
SELECT product_id, name, price_cents, date_created, date_modified FROM product_info
`

func (q *Queries) GetProducts(ctx context.Context) ([]ProductInfo, error) {
	rows, err := q.db.Query(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductInfo
	for rows.Next() {
		var i ProductInfo
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.PriceCents,
			&i.DateCreated,
			&i.DateModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrice = `-- name: UpdatePrice :exec
UPDATE product_info
SET price_cents = $1
WHERE product_id = $2
`

type UpdatePriceParams struct {
	PriceCents int32
	ProductID  pgtype.UUID
}

func (q *Queries) UpdatePrice(ctx context.Context, arg UpdatePriceParams) error {
	_, err := q.db.Exec(ctx, updatePrice, arg.PriceCents, arg.ProductID)
	return err
}
