// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionRows = `-- name: CountTransactionRows :one
SELECT COUNT(*) from transactions
`

func (q *Queries) CountTransactionRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionRows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransactions = `-- name: GetTransactions :many

SELECT
    t.transaction_id,
    t.price_at_sale_cents,
    t.date_sold,
    p.name
FROM transactions as t
JOIN product_info p ON t.product_id = p.product_id
ORDER BY t.date_sold DESC
LIMIT $2
OFFSET $1
`

type GetTransactionsParams struct {
	PageOffset int32
	NumRows    int32
}

type GetTransactionsRow struct {
	TransactionID    pgtype.UUID
	PriceAtSaleCents int32
	DateSold         pgtype.Timestamptz
	Name             string
}

// code: language=postgres
func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]GetTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getTransactions, arg.PageOffset, arg.NumRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.PriceAtSaleCents,
			&i.DateSold,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
