// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentTransactions = `-- name: GetRecentTransactions :many
SELECT
    t.transaction_id,
    t.price_at_sale,
    t.date_sold,
    p.name
FROM transactions as t
JOIN product_info p ON t.product_id = p.product_id
ORDER BY t.date_sold DESC
LIMIT $1
`

type GetRecentTransactionsRow struct {
	TransactionID pgtype.UUID
	PriceAtSale   pgtype.Numeric
	DateSold      pgtype.Timestamptz
	Name          string
}

func (q *Queries) GetRecentTransactions(ctx context.Context, numRows int32) ([]GetRecentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, numRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentTransactionsRow
	for rows.Next() {
		var i GetRecentTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.PriceAtSale,
			&i.DateSold,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
